### PR TITLE
Reducing Matrix Size for `test_Cached_SymmetricStructure`

### LINKED ISSUE #10: `ctest_Cached_SymmetricStructure` LC Crash
# General
This is a spinoff of https://github.com/emusolutions/LAGraph/issues/4 to tackle the problems with `ctest_Cached_SymmetricStructure`.

# Details

```
 ctest --test-dir build_lc -R ctest_Cached_SymmetricStructure -V
Internal ctest changing into directory: /net/hyper120h-d/data/jsmith/apps/LAGraph/build_lc
UpdateCTestConfiguration  from :/net/hyper120h-d/data/jsmith/apps/LAGraph/build_lc/DartConfiguration.tcl
UpdateCTestConfiguration  from :/net/hyper120h-d/data/jsmith/apps/LAGraph/build_lc/DartConfiguration.tcl
Test project /net/hyper120h-d/data/jsmith/apps/LAGraph/build_lc
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 6
    Start 6: ctest_Cached_SymmetricStructure

6: Test command: /usr/bin/cmake "-E" "env" "/tools/lucata/bin/emusim.x" "--forward_return_value" "--" "test_Cached_SymmetricStructure" "--no-exec"
6: Test timeout computed to be: 10000000
6:
6:         SystemC 2.3.3-Accellera --- Apr 21 2023 11:46:50
6:         Copyright (c) 1996-2018 by all Contributors,
6:         ALL RIGHTS RESERVED
6: Test test_Symmetric_Structure...                Selected mode is not availble on this architecture. Setting mode to GrB_BLOCKING.[ FAILED ]
6:   Case comments_west0067.mtx:
6:     test_Cached_SymmetricStructure.c:136: Check LAGraph_MMRead (&A, f, msg) == 0... failed
6:     test_Cached_SymmetricStructure.c:145: Check LAGraph_Cached_IsSymmetricStructure (G, msg) == 0... failed
6:     test_Cached_SymmetricStructure.c:154: Check G->is_symmetric_structure == LAGraph_FALSE... failed
6:     test_Cached_SymmetricStructure.c:161: Check LAGraph_Cached_AT (G, msg) == 0... failed
6:     test_Cached_SymmetricStructure.c:162: Check LAGraph_Cached_IsSymmetricStructure (G, msg) == 0... failed
6:     test_Cached_SymmetricStructure.c:171: Check G->is_symmetric_structure == LAGraph_FALSE... failed
6:
6: status: -2, msg: LAGraph assertion "G != ((void*)0)" failed (file /net/hyper120h-d/data/jsmith/apps/LAGraph/src/utility/LAGraph_Cached_IsSymmetricStructure.c, line 43): status: -2
6: FAILED: 1 of 1 unit tests has failed.
1/1 Test #6: ctest_Cached_SymmetricStructure ...***Failed  330.51 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) = 330.51 sec

The following tests FAILED:
          6 - ctest_Cached_SymmetricStructure (Failed)
Errors while running CTest
Output from these tests are in: /net/hyper120h-d/data/jsmith/apps/LAGraph/build_lc/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

### PR DESCRIPTION
**Pull request by jamesETsmith**
# General

This is essentially the same as #11. I missed that `test_Cached_SymmetricStructure` also used larger matrices. This fixes #10.

### CODE REVIEW

File: src/test/test_TriangleCount.c [hunk 1]
```diff
@@ -40,12 +40,12 @@ const matrix_info files [ ] =
...
     {     45, "karate.mtx" },
     {     11, "A.mtx" },
-    {   2016, "jagmesh7.mtx" },
+    // {   2016, "jagmesh7.mtx" },
     {      6, "ldbc-cdlp-undirected-example.mtx" },
     {      4, "ldbc-undirected-example.mtx" },
     {      5, "ldbc-wcc-example.mtx" },
     {      0, "LFAT5.mtx" },
-    { 342300, "bcsstk13.mtx" },
+    // { 342300, "bcsstk13.mtx" },
```
Comment (jamesETsmith) [inline src/test/test_TriangleCount.c:48]: @mcordery, these two are just larger matrices that drastically slow things down in the simulator. You may want to uncomment `jagmesh7.mtx` after you get things working, I think `bcsstk13.mtx` will probably be too big to be worth it down the line so we can leave it commented.

File: src/test/test_TriangleCount.c [hunk 2]
```diff
@@ -482,7 +482,7 @@ TEST_LIST = {
     {"TriangleCount_Methods6", test_TriangleCount_Methods6},
     {"TriangleCount"         , test_TriangleCount},
     {"TriangleCount_many"    , test_TriangleCount_many},
-    {"TriangleCount_autosort", test_TriangleCount_autosort},
+    // {"TriangleCount_autosort", test_TriangleCount_autosort},
```
Comment (jamesETsmith) [inline src/test/test_TriangleCount.c:485]: @mcordery, `TriangleCount_autosort` created a bigger matrix in memory and _I believe_, was the cause of the LC crash reported in #13.
